### ISSUE TITLE
BOT doesn’t add the emoji

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [peterthehan/discord-reaction-role-bot#11]
I got the project running it works except for that the bot doesn’t add the emoji reaction to the message.

I am currently on mobile, I can look into the project myself tomorrow but if you know a quick fix please let me know :)

Your projects look awesome btw! :) 

For anyone who has a problem with: “AbortController is not defined” make sure you are using the latest JS version.

check node version: 
> node -v

For using Discord.js v13 is that you need to use NodeJS v16.6 or higher 

fix:
> npm install -g n
> n latest

**Comment by sanderDijkxhoorn** [comment]
Havn't changed anything but it works now 😓

**Comment by peterthehan** [comment]
Glad it worked out, I'll add an additional readme note for the node version.
