### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Diondz** [peterthehan/discord-reaction-role-bot#12]
This is being so all people
npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/discord-reaction-role-bot/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/discord-reaction-role-bot/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! /home/runner/.npm/_logs/2022-01-04T09_30_19_818Z-debug.log
exit status 254


**Comment by peterthehan** [comment]
Stale, please open a new issue or visit the server for troubleshooting.
