### ISSUE TITLE
Custom emojis documentation

### ISSUE THREAD

**Issue by LemADEC** [peterthehan/discord-reaction-role-bot#3]
The readme says we should use the 'emoji id' for custom emojis. Practically, it doesn't say how to get input that emoji id and report them as "unknown".
For example, I've a :cyan_ship: custom emoji, but the bot is errorring when I try use `cyan_ship` or `:cyan_ship:` as an id.
To get the actual id, ones need to escape the emoji. So in my case, I had to type `\:cyan_ship:` in discord to see the id to use.

**Comment by peterthehan** [comment]
Agreed that it can be more clear.

**Comment by peterthehan** [comment]
README should be more clear now. I included ways the user can grab the emoji for either unicode or custom emojis and provided examples of what it may look like for reference.
