### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'roles' of undefined

### ISSUE THREAD

**Issue by MarquesCoding** [peterthehan/discord-reaction-role-bot#6]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'roles' of undefined

**Comment by peterthehan** [comment]
Seems like a config issue, can you post your config file contents?

**Comment by peterthehan** [comment]
Stale. Please visit the server if you need further troubleshooting.
